Userモデルの実装
ok-os-job-change-team/kaito-twitter-clone-bootcamp pull request #11
Opened 2023-09-06 14:44 UTC by Kaito1290

## 概要
- userテーブルの実装（db/schema.rb）
- 初期データの設定(db/seeds.rb)
- Userモデルの実装(app/models/user.rb)

## 関連Issue
- https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/issues/2

2023-09-10 13:34 UTC, Kaito1290 commented
i18nの導入しました
以下、rspecのテスト結果です
``` bash
root@7aa902b37526:/app# bundle exec rspec spec/models/user_valid_spec.rb

User
  #presenseメソッド
    emailが存在する場合
      valid?がtrueになる
    emailが空文字の場合
      errorsに「メールアドレスを入力してください」と格納される
    emailがnilの場合
      errorsに「メールアドレスを入力してください」と格納される
    passwordが存在する場合
      valid?がtrueになる
    passwordが空文字の場合
      errorsに「パスワードを入力してください」と格納される
    passwordがnilの場合
      errorsに「パスワードを入力してください」と格納される

Finished in 0.61264 seconds (files took 6.3 seconds to load)
6 examples, 0 failures
```

2023-09-11 13:33 UTC, ochi-sho-private-study requested changes
@Kaito1290 
コメントしました〜

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/ja.yml
> +      wrong_length: は%{count}文字で入力してください
この記述は必要になったら足す、という形でいいかと思う！
今回だと、blankだけ必要かな！

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/ja.yml
> +    - 土曜日
今は必要ないので、消そう

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/ja.yml
> +    - :day
必要ないので、消そう

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/ja.yml
> +      year: 年
必要ないので、消そう

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/ja.yml
> +          unit: ''
今は必要ないので、消そう！

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/ja.yml
> +    pm: 午後
今は必要ないので、消そう！

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/admin/dashboards/ja.yml
このファイルは何に使うのかな？
必要ないのであれば、消そう！

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/admin/ja.yml
このファイルは必要？

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/admin/user_sessions/ja.yml
このファイルは必要かな？

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/admin/users/ja.yml
このファイルは必要かな？

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/boards/ja.yml
このファイルは必要かな？

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/password_resets/ja.yml
このファイルは必要かな？

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/shared/ja.yml
このファイルは必要かな？

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/user_sessions/ja.yml
このファイルは必要かな？

2023-09-11 13:33 UTC, ochi-sho-private-study commented on config/locales/views/users/ja.yml
このファイルは必要かな？

2023-09-11 13:33 UTC, ochi-sho-private-study commented on spec/models/user_valid_spec.rb
> +    end
`ActiveRecord::Base`を継承したクラスを用いてRspecを書く場合は、FactoryBotを使おう 👀 
また、letを使おう。

```suggestion
    context 'emailが存在する場合' do
      let(:user) { build(:user, email: 'hoge@example.com') }

      it 'valid?がtrueになる' do
        expect(user.valid?).to eq true
      end
    end
```

2023-09-11 13:33 UTC, ochi-sho-private-study commented on spec/models/user_valid_spec.rb
> +    end
同じitブロック内でいいので、user.valid?の結果がfalseになることもテストしよう。

2023-09-12 13:47 UTC, Kaito1290 commented on app/controllers/messages_controller.rb
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:50 UTC, Kaito1290 commented on app/models/user.rb
> +  validates :email, :password, presence: true
下記コミットで修正しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:50 UTC, Kaito1290 commented on config/locales/ja.yml
> +        admin: 管理者フラグ
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:51 UTC, Kaito1290 commented on config/locales/ja.yml
> +        name: 名前
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:51 UTC, Kaito1290 commented on config/locales/ja.yml
> +      wrong_length: は%{count}文字で入力してください
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:51 UTC, Kaito1290 commented on config/locales/ja.yml
> +    - 土曜日
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:51 UTC, Kaito1290 commented on config/locales/ja.yml
> +    - :day
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:51 UTC, Kaito1290 commented on config/locales/ja.yml
> +      year: 年
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:52 UTC, Kaito1290 commented on config/locales/ja.yml
> +          unit: ''
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:52 UTC, Kaito1290 commented on config/locales/ja.yml
> +    pm: 午後
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:52 UTC, Kaito1290 commented on config/locales/views/admin/dashboards/ja.yml
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:52 UTC, Kaito1290 commented on config/locales/views/admin/ja.yml
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:52 UTC, Kaito1290 commented on config/locales/views/admin/user_sessions/ja.yml
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:52 UTC, Kaito1290 commented on config/locales/views/admin/users/ja.yml
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:53 UTC, Kaito1290 commented on config/locales/views/password_resets/ja.yml
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:53 UTC, Kaito1290 commented on config/locales/views/shared/ja.yml
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 13:53 UTC, Kaito1290 commented on config/locales/views/users/ja.yml
下記コミットで削除しました。
55133ec42eafd84c76c09fcc102e12d4192f7687

2023-09-12 14:50 UTC, Kaito1290 commented on spec/models/user_valid_spec.rb
> +    end
以下のコミットで修正しました。
97ab26e842337cfcb3f485700d4870ab6b95bbbe

- テスト結果
  ```bash
    root@7aa902b37526:/app# bundle exec rspec spec/models/user_valid_spec.rb
    
    User
      #presenseメソッド
        emailが存在する場合
          valid?がtrueになる
        emailが空文字の場合
          valid?がfalseになる
          errorsに「メールアドレスを入力してください」と格納される
        emailがnilの場合
          valid?がfalseになる
          errorsに「メールアドレスを入力してください」と格納される
        passwordが存在する場合
          valid?がtrueになる
        passwordが空文字の場合
          valid?がfalseになる
          errorsに「パスワードを入力してください」と格納される
        passwordがnilの場合
          valid?がfalseになる
          errorsに「パスワードを入力してください」と格納される
    
    Finished in 0.57002 seconds (files took 6.38 seconds to load)
    10 examples, 0 failures
  ```

2023-09-12 16:58 UTC, ochi-sho-private-study reviewed
@Kaito1290 
コメントした！
（コメント箇所を修正できたらLGTM!）

2023-09-12 16:58 UTC, ochi-sho-private-study commented on db/seeds.rb
> +User.create(email:'shoichi@example.com', password:'hohogege', created_at:'2023-08-10' ,updated_at:'2023-09-01')
ここ、created_atとupdated_atは指定しなくてもいいと思う！
(指定しない場合、created_atとupdated_atには現在の時刻が入る)

2023-09-12 16:58 UTC, ochi-sho-private-study commented on docs/validation.md
> +- RailsはActiveRecordオブジェクトを保存する直前にバリデーションを実行する
厳密に言うと、以下だと思う！
（ActiveRecordオブジェクトを保存する訳ではない。）
```suggestion
- Railsでは、レコードを保存する直前にバリデーションを実行することができる。
  - ActiveRecord::Baseを継承したメソッドでは、レコードを保存する前に自動的にバリデーションが実行される。
```

2023-09-12 16:58 UTC, ochi-sho-private-study commented on docs/validation.md
> +- バリデーション実行後に`errors`メソッドを使うことで、発生したエラーメッセージを取得できる
エラーメッセージではないかな！
例えば、`user.errors`を実行すると、
ActiveModel::Errorsクラスのインスタンスが帰ってくると思う！

2023-09-12 16:58 UTC, ochi-sho-private-study commented on spec/models/user_valid_spec.rb
> +      end
以下のように、同じitブロックでテストするようにすると、少しテスト実行速度が速くなるよ〜
```suggestion
      it 'valid?がfalseになる' do
        aggregate_failures do
          result = user.valid?
          expect(result).to eq false
          expect(user.errors.full_messages).to include('メールアドレスを入力してください')
        end
      end
```

---

### aggregate_failuresブロックについて
https://blog.solunita.net/posts/easy-to-write-rspec-by-aggregate-failures-and-request-describer/

2023-09-13 14:13 UTC, Kaito1290 commented on docs/validation.md
> +- バリデーション実行後に`errors`メソッドを使うことで、発生したエラーメッセージを取得できる
ほんとだー
```bash
irb(#<RSpec::ExampleGroups::User:...):001> user.errors
=> #<ActiveModel::Errors [#<ActiveModel::Error attribute=email, type=blank, options={}>]>
```

2023-09-13 14:21 UTC, Kaito1290 commented on db/seeds.rb
> +User.create(email:'shoichi@example.com', password:'hohogege', created_at:'2023-08-10' ,updated_at:'2023-09-01')
下記コミットで修正しました。
a530545b09f09e38c401098df505d86d29e7db5f

2023-09-13 14:23 UTC, Kaito1290 commented on docs/validation.md
> +- RailsはActiveRecordオブジェクトを保存する直前にバリデーションを実行する
下記コミットで修正しました（user_valid_spec.rbの修正は無視してください）
58a48eef3a58c559b0c077812c5498dc1681775c

2023-09-13 14:23 UTC, Kaito1290 commented on docs/validation.md
> +- バリデーション実行後に`errors`メソッドを使うことで、発生したエラーメッセージを取得できる
下記コミットで修正しました（user_valid_spec.rbの修正は無視してください）
58a48eef3a58c559b0c077812c5498dc1681775c

2023-09-15 12:29 UTC, Kaito1290 commented on spec/models/user_valid_spec.rb
> +      end
下記コミットで修正しました。
cead289ebe4ad6c3fd045d3df4c5c83c83d814aa

- 実行結果
```bash
root@42dfc1790793:/app# bundle exec rspec spec/models/user_valid_spec.rb

User
  #presenseメソッド
    emailが存在する場合
      valid?がtrueになる
    emailが空文字の場合
      valid?がfalseになり、errorsに「メールアドレスを入力してください」と格納される
    emailがnilの場合
      valid?がfalseになり、errorsに「メールアドレスを入力してください」と格納される
    passwordが存在する場合
      valid?がtrueになる
    passwordが空文字の場合
      valid?がfalseになり、errorsに「パスワードを入力してください」と格納される
    passwordがnilの場合
      valid?がfalseになり、errorsに「パスワードを入力してください」と格納される

Finished in 0.59662 seconds (files took 6.68 seconds to load)
6 examples, 0 failures
```

2023-09-16 02:07 UTC, ochi-sho-private-study approved these changes
@Kaito1290 
コメント箇所修正したらLGTM!

2023-09-16 02:07 UTC, ochi-sho-private-study commented on spec/models/user_valid_spec.rb
> +          expect(user.errors.full_messages).to include('パスワードを入力してください')
以下の方がより信頼性のあるテストになるよ〜

includeの場合は、`'パスワードを入力してください'`という文字列が要素に含まれる、ということだけテストしているので、`user.errors.full_messages`に他のメッセージが含まれていてもテストが通ってしまうんよね。
```suggestion
          expect(user.errors.full_messages).to eq ['パスワードを入力してください']
```

2023-09-16 07:07 UTC, Kaito1290 commented on spec/models/user_valid_spec.rb
> +          expect(user.errors.full_messages).to include('パスワードを入力してください')
配列のまま渡して判定に使えるのかー

下記コミットで修正しました
965c1b71fc314f513a280ced1eae719e30059d20

2023-09-16 13:38 UTC, ochi-sho-private-study commented on spec/models/user_valid_spec.rb
> +          expect(user.errors.full_messages).to include('パスワードを入力してください')
@Kaito1290 
eqだと使えるね！

2023-09-16 13:38 UTC, ochi-sho-private-study commented
@Kaito1290 
LGTM！

2023-09-16 15:14 UTC, merged