userコントローラー(create)の実装
ok-os-job-change-team/kaito-twitter-clone-bootcamp pull request #23
Opened 2023-09-20 13:49 UTC by Kaito1290

## 概要
- UsersControllerの実装
  - newアクション
  - createアクション
- view(ユーザー作成画面)の実装
  - メールアドレスとパスワードの入力フォーム
  - ユーザー作成ボタン

## 関連Issue
- https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/issues/4
-

2023-09-20 13:49 UTC, Kaito1290 commented
rspecは明日実装します。

2023-09-22 13:41 UTC, ochi-sho-private-study commented on spec/requests/users_create_spec
> +          user.posts.create( :user )
```suggestion
          post users_path, params: { user: { email: 'kaito@example.com', password: 'password' } }
```

2023-09-22 14:01 UTC, ochi-sho-private-study commented on spec/requests/users_create_spec
> +          user.posts.create( :user )
```ruby
let(params) do
  { email: 'kaito@example.com', password: 'password' }
end
```

2023-09-22 14:23 UTC, ochi-sho-private-study commented on app/controllers/users_controller.rb
> +    redirect_to '/users'
```suggestion
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '作成に成功しました'
      redirect_to '/users'
    else
      render 'new'
    end
```

2023-09-25 15:09 UTC, Kaito1290 commented
flashメッセージを途中まで実装
renderが動きません

2023-09-26 14:43 UTC, Kaito1290 commented
＜実装できていないところ＞
- ユーザー登録失敗時のflashメッセージが表示されない。

＜試したこと、わかっていること＞
- renderメソッドを使って指定したテンプレートは呼び出せている
- renderはflash.now[:key]、redirect_toはflash[:key]と使うで間違ってなさそう
 - flash.now[:key]は次のアクションが実行されるまで表示
 - flash[:key]は アクションが実行後、次のアクションが実行されるまで表示
- 不具合の原因はflash.now[:key]がうまく機能していないため？
 - form_with（ヘルパーメソッド） に、local: true オプションをつけてみたが解決せず...

2023-09-26 17:23 UTC, ochi-sho-private-study commented
ごめん、失敗時はflashメッセージだけではなくて、バリデーションエラーメッセージも表示したい！
```erb
<h1>新規ユーザー登録</h1>

<%= form_with model: @user, url: users_path, local: true, data: { turbo: "false" } do |form| %>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>

  <table>
    <tr>
      <th>メールアドレス</th>
      <td><%= form.text_field :email %></td>
    </tr>
    <tr>
      <th>パスワード</th>
      <td><%= form.text_field :password %></td>
    </tr>

    <tr>
      <th></th>
      <td><%= form.submit '送信' %></td>
    </tr>
  </table>
<% end %>
```

2023-09-28 14:41 UTC, Kaito1290 commented on spec/requests/users_create_spec
> +          user.posts.create( :user )
RSpecは下記コミットで確認お願いします。
[d1805cb](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/23/commits/d1805cb684f7ce3beaaf095227d6e5388c984573)

2023-09-28 14:43 UTC, Kaito1290 commented on app/controllers/users_controller.rb
> +    redirect_to '/users'
下記コミットで修正しました
[d71a050](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/23/commits/d71a050fb5f97ccd7408461892f37a45b307b0c0)

2023-09-30 03:21 UTC, ochi-sho-private-study requested changes
@Kaito1290 
コメントした！

2023-09-30 03:21 UTC, ochi-sho-private-study commented on config/locales/models/user/ja.yml
> +              blank: を入力してください
以下の方が簡潔かと思う！
```suggestion
    errors:
    messages:
      blank: を入力してください
```

2023-09-30 03:21 UTC, ochi-sho-private-study commented on spec/requests/users_create_spec
> +require 'rails_helper'
これって必要なのかね？

2023-09-30 03:21 UTC, ochi-sho-private-study commented on spec/requests/users_create_spec
Idiomatic

ファイル名は、`spec/requests/users_controller_spec.rb`にしよう〜

2023-09-30 03:21 UTC, ochi-sho-private-study commented on spec/requests/users_read_spec.rb
Idiomatic

ファイル名は、`spec/requests/users_controller_spec.rb`にしよう〜
(READとCREATEのRspecは同ファイルに書こう。)

2023-09-30 03:21 UTC, ochi-sho-private-study commented on app/views/users/_alert.html.erb
このファイルは使われてないような気がする！

2023-09-30 03:24 UTC, ochi-sho-private-study commented on spec/requests/users_create_spec
> +          expect(response.body).to include '登録に失敗しました'
テストケースは以下の2つだけでいいと思う！
また、`作成に失敗し、バリデーションエラーになる場合`は、Userのcountが変更されないことを確認しよう！

- 正常に作成される場合(`@user.save`がtrueになるとき)
- 作成に失敗し、バリデーションエラーになる場合(`@user.save`がfalseになるとき)

2023-09-30 03:28 UTC, ochi-sho-private-study commented on app/controllers/users_controller.rb
> +  def user_params
スペースを開けよう
```suggestion
  private

  def user_params
```

2023-09-30 13:46 UTC, Kaito1290 commented on spec/requests/users_create_spec
> +require 'rails_helper'
記述をコメントアウトしてもテスト通ったけど、基本的に記述するものだと思ってました。
質問に質問で返して申し訳ないのですが、今回のテストでは他のモデルと関連した動作とかないから、記述なしでも問題ないということでしょうか？

- https://zenn.dev/airiswim/articles/05a1334c031b51#:~:text=%E5%90%84%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E5%85%88%E9%A0%AD%E3%81%AB%E3%80%81%E5%BF%85%E3%81%9A%20require%20%22rails_helper%20%E3%82%92%E8%A8%98%E8%BF%B0%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%80%82

2023-09-30 14:20 UTC, Kaito1290 commented on config/locales/models/user/ja.yml
> +              blank: を入力してください
下記コミットで修正しました
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/23/commits/4a017d587b4aa822b10de484662cb47759f02415

2023-09-30 14:21 UTC, Kaito1290 commented on app/views/users/_alert.html.erb
確かに！
迷走してた時の残骸です...
下記コミットで削除しました。
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/23/commits/dbf4e2a770853abb9bf69b235b8e974a9fe97f4b

2023-09-30 14:22 UTC, Kaito1290 commented on spec/requests/users_create_spec
> +          expect(response.body).to include '登録に失敗しました'
下記コミットで修正しました。
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/23/commits/5cced0f525125e53fdb40d1efdf53a8466a7b1ed

2023-09-30 14:23 UTC, Kaito1290 commented on app/controllers/users_controller.rb
> +  def user_params
下記コミットで修正しました。
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/23/commits/5cced0f525125e53fdb40d1efdf53a8466a7b1ed

2023-09-30 14:26 UTC, Kaito1290 commented
下記コミットでコード内に残っていた`binding.irb`を削除しました。

2023-10-01 04:49 UTC, ochi-sho-private-study commented on spec/requests/users_create_spec
> +require 'rails_helper'
以下のファイル上でrequireの記述をしているので、
specファイルには記述する必要はない、って感じかな！
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/blob/main/.rspec

Ref: https://stackoverflow.com/questions/72070371/rails-how-to-configure-rspec-so-you-do-not-need-to-require-rails-helper

2023-10-01 04:54 UTC, ochi-sho-private-study reviewed
@Kaito1290 
返信とコメントしたよ！
- https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/23#discussion_r1342074510

---

また、ユーザー一覧画面に「新規登録」ボタンを追加して、`users/new`に遷移できるようにしよう！

2023-10-01 04:54 UTC, ochi-sho-private-study commented on app/controllers/users_controller.rb
> +
Readable

この空白は消そう

2023-10-01 04:54 UTC, ochi-sho-private-study commented on app/controllers/users_controller.rb
> +    # つまり、user内にemailとpasswordがあるかどうかを確認している
そうではなく、user内にあるemailとpasswordだけ取得する、という感じやね。
例えば、paramsが以下のような構造だったとしても、
emailとpasswordだけ取得される。

```ruby
{
  user: { 
    email: 'hoge@example.com'
    password: 'password',
    gender: '男性',
    note: '備考'
  }
}
```

2023-10-01 04:54 UTC, ochi-sho-private-study commented on spec/requests/users_read_spec.rb
このファイルが削除されていない気がする

2023-10-08 03:39 UTC, ochi-sho-private-study approved these changes
@Kaito1290 
コメント箇所修正したらLGTM!
あと、新規登録ボタンの動作確認の動画もPRの説明欄に貼っておいてほしい！

2023-10-08 03:39 UTC, ochi-sho-private-study commented on config/locales/models/user/ja.yml
他のモデルの日本語も定義するとしたら、
ファイル名は`config/locales/ja.yml`がいいんじゃないかな？

2023-10-10 14:18 UTC, Kaito1290 commented on config/locales/models/user/ja.yml
下記コミットで修正しました
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/23/commits/692fccd5543c1fb1f7873925a106198df1589052

2023-10-12 15:42 UTC, merged