デバッグ用にbinding.pryを使えるようにする
ok-os-job-change-team/kaito-twitter-clone-bootcamp pull request #26
Opened 2023-10-14 05:31 UTC by Kaito1290

2023-10-15 06:12 UTC, ochi-sho-private-study requested changes
@Kaito1290 
コメントしました〜

2023-10-15 06:12 UTC, ochi-sho-private-study commented on docs/binding_pry.md
> +**webアプリの動作を試すとき**
docker環境ではないrailsアプリでは、attachする必要がないので、以下の記述が適切ですね〜
(docker環境ではないrailsアプリでは、ホストマシン上で`rails s`コマンドを実行するため、stdinがインタラクティブである。)
```suggestion
**docker環境のrailsアプリにアクセスした時**
```

2023-10-17 13:36 UTC, Kaito1290 commented on .vscode/settings.json
下記コミットで修正しました
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/26/commits/3620190b55ad772bd2960d61baedf72259ca1592

2023-10-17 13:37 UTC, Kaito1290 commented on app/controllers/users_controller.rb
> +    binding.pry
下記コミットで修正しました
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/26/commits/3620190b55ad772bd2960d61baedf72259ca1592

2023-10-17 13:37 UTC, Kaito1290 commented on docs/binding_pry.md
> +```gemfile
下記コミットで修正しました
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/26/commits/3620190b55ad772bd2960d61baedf72259ca1592

2023-10-17 13:37 UTC, Kaito1290 commented on docs/binding_pry.md
> +**webアプリの動作を試すとき**
下記コミットで修正しました
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/26/commits/3620190b55ad772bd2960d61baedf72259ca1592

2023-10-17 14:11 UTC, ochi-sho-private-study commented on .vscode/settings.json
このファイルは不要だと思う

2023-10-17 14:39 UTC, ochi-sho-private-study approved these changes
@Kaito1290 
lgtm

2023-10-18 13:11 UTC, merged