ユーザーをフォローする機能を実装する
ok-os-job-change-team/kaito-twitter-clone-bootcamp pull request #57
Opened 2023-12-25 08:26 UTC by Kaito1290

## 機能要件
- ログインしているユーザーは、自身以外のユーザーをフォローできる
- ログインしているユーザーは、フォローしている自身以外のユーザーをフォロー解除できる
- ユーザー詳細画面でフォロー・フォロワー数を見ることができる
- フォローリスト画面、フォロワーリスト画面を用意する

## 概要
### テーブル
- Relationshipsテーブルの実装(db/schema.rb)
  - カラムは`id`, `following_id`, `follower_id`
- Relationshipsテーブル初期データの設定(db/seeds.rb)

### モデル
- Relationshipモデル(app/models/relationship.rb)
  - Userモデルを親モデルとして擬似的にFollowモデルとFollowerモデルを作成する
  - RelationshipモデルにはUserモデルとのアソシエーションを設定する
- Userモデル(app/models/user.rb)
  - UserモデルにはとRelationshipモデルとのアソシエーションを設定する

### ルーティング
- `ralationships`は親モデルのUserのidが必要なので、`users`の中にネストする
- フォローリスト画面、フォロワーリスト画面へのルーティングを作る

### コントローラー
- Relationshipsコントローラーを実装(app/controllers/relationships_controller)
  - createアクション
  - destroyアクション
- Usersコントローラーの修正(app/controllers/users_controller)
  - followsアクション追加
  - followersアクション追加

### ビュー
- ユーザーリスト(app/views/users/index.html.erb)
  - フォローボタン、フォロー解除ボタンを実装
- フォローリスト画面を実装(app/views/users/follows.html.erb)
- フォロワーリスト画面を実装(app/views/users/followers.html.erb)

### テスト
- Relationshipモデルのテストを実装(spec/models/relationship_spec.rb)
- Relationconshipコントローラーのテストを実装(spec/requests/relationships_controller_spec.rb)

2024-01-06 06:33 UTC, Kaito1290 commented on db/schema.rb
> +  end
`app/models/user.rb`に外部キー制約付けてるのとは別に必要ってこと？

```ruby
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates :password, presence: true

  has_many :tweets
  has_many :favorites
  # <Userモデルのインスタンス>.favorite_tweetsでいいねしたツイートを取得する
  has_many :favorite_tweets, through: :favorites, source: :tweet

  # フォローする側のUserからみたRelationshipをactive_relationshipとする
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  # 中間テーブルを介してUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower

  # フォローされる側のUserからみたRelationshipをpassive_relationshipとする
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id
  # 中間テーブルを介してUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    # フォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
end
```

2024-01-20 08:36 UTC, ochi-sho-private-study requested changes
@Kaito1290 
コメントした！

2024-01-24 05:16 UTC, Kaito1290 commented on db/schema.rb
> +  end
アソシエーションと外部キー制約を勘違いしてた。
下記コミットで追加しました。
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/57/commits/a35fd1437eb1f4b98401809d059a5e9095ee0092

以下に外部キー制約必要そうだけど、これはフォロー機能のブランチだから追加しない方がいい感じ？
FavoritesテーブルとUsersテーブル
FavoritesテーブルとTweetsテーブル

2024-01-25 14:14 UTC, ochi-sho-private-study commented on db/schema.rb
> +  end
追加した外部キー制約は、relationshipsテーブルのものではないので違うよ。
（もちろん必要なものではあるんだけど、今回の変更内容には関係がないということ。）

僕が言いたかったのは、以下のような外部キー制約のことだね。
```ruby
add_foreign_key "relationships", "users", column: "following_id"
add_foreign_key "relationships", "users", column: "follower_id"
```

---

> 以下に外部キー制約必要そうだけど、これはフォロー機能のブランチだから追加しない方がいい感じ？
> FavoritesテーブルとUsersテーブル
> FavoritesテーブルとTweetsテーブル

別issueを切って、そのissueで対応しようか。

2024-01-26 02:09 UTC, Kaito1290 commented on db/schema.rb
> +  end
下記コミットで修正しました
[75b56c7](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/57/commits/75b56c7259aeedd934e94e355d2e7480ef48d20f)

relationshipsテーブル以外の外部キー制約は下記PRで修正しました
- https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/84

2024-01-27 16:12 UTC, ochi-sho-private-study reviewed
@Kaito1290 
コメントしたよ

2024-01-27 16:12 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
idiomaticの観点/ユーザー視点での観点

`current_user.active_relationships.find_by(follower_id: params[:user_id])`がnilになるときはどうなるかな？
（404ページに遷移させた方がいいんじゃないかな？404ページの作成は別issueでやるとしても、今回は例外をraiseした方がいいんじゃないかな？）

2024-01-27 16:12 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +    follow.save
画面からだとまずないだろうけど、
バリデーションエラーになった時はどうするのかな？

2024-01-29 13:26 UTC, Kaito1290 commented on app/controllers/relationships_controller.rb
> +    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
下記コミットで修正しました
[43d1bd8](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/57/commits/43d1bd8f1412f68d9ddaadac85291bb6a17533d6)

[baa430b](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/57/commits/baa430ba825ab07d7a5a61521757c946bbe9612f)

2024-01-29 14:38 UTC, ochi-sho-private-study approved these changes
@Kaito1290 
コメント箇所修正したらLGTM!

2024-01-29 14:38 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +    follow = find_follow(params[:user_id])
IMO

メソッドに切り分けるほどでもないと思う！
```suggestion
    follow = \
      current_user.active_relationships.find_by!(follower_id: params[:user_id])
```

2024-01-29 14:38 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +  end
render_not_foundの方が意味合い的には適切だと思うのと、
ApplicationControllerでrescue_fromしてるのであれば、
このrescueは必要ないんじゃない？

2024-01-30 01:10 UTC, Kaito1290 commented on app/controllers/relationships_controller.rb
> +    follow = find_follow(params[:user_id])
rubocopの`Metrics/AbcSize`に引っかかったからメソッド切り分けたけど
逆にわかりづらくなってた気がしてた...
メソッド元に戻してrubocop_todo.ymlで制限緩くしました。
[a7aa4eb](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/57/commits/a7aa4eb1560c611aaaf7f8d89b06910fd694a357)

2024-01-30 01:13 UTC, Kaito1290 commented on app/controllers/relationships_controller.rb
> +  end
resucueとrescue_fromの使い方調べたけど、よく分かんなくて両方使ってた...
[a7aa4eb](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/pull/57/commits/a7aa4eb1560c611aaaf7f8d89b06910fd694a357)

2024-01-30 13:26 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +    follow = find_follow(params[:user_id])
rubocop_todo.ymlで制限を緩くするのはやめよう

2024-01-30 13:29 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +  end
rescue_fromに関しては、以下の記事を見たらわかる。
rescueをまとめてくれる便利なメソッドって感じ。

https://prograshi.com/framework/rails/rescue_from/

2024-01-30 15:34 UTC, ochi-sho-private-study approved these changes
LGTM!

2024-01-31 00:22 UTC, merged